name = "bbc-english-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "bbc-english-db"
database_id = "472637fc-3d79-4f53-b351-55a417b02421"

[triggers]
crons = ["0 */6 * * *"]

[vars]
RSS_FEED_URL = "https://feeds.bbci.co.uk/learningenglish/english/features/6-minute-english_2026/rss"
BBC_BASE_URL = "https://www.bbc.co.uk/learningenglish/english/features/6-minute-english"
ADMIN_SECRET = "debug2026"
